<a href="https://colab.research.google.com/github/JebaMercy14/AI-Spartificial-Course/blob/main/Numpy_and_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **NumPy**

1. NumPy is a Python library for scientific computing in Python. 
2. It contains a collection of tools and techniques that can be used to solve on a computer mathematical models of problems in Science and Engineering. 
3. One of these tools is a high-performance multidimensional array object that is a powerful data structure for efficient computation of arrays and matrices. 
4. To work with these arrays, there’s a vast amount of high-level mathematical functions operate on these matrices and arrays.

In [1]:
import numpy as np 
np.__version__

'1.21.6'

In [2]:
# Make the array `my_array`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_array)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
# Create an array of ones
a = np.ones((3,4))

# Create an array of zeros
b = np.zeros((2,3,4))

# Create an array with random values
c = np.random.random((2,2))

# Create an empty array
d = np.empty((3,2))

# Create a full array
e = np.full((2,2),7)

# Create an array of evenly-spaced values
f = np.arange(10,25,3)

# Create an array of evenly-spaced values
g = np.linspace(0,2,9)

In [4]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0.01074134 0.86016003]
 [0.68033778 0.42858468]]
[[1.8194849e-316 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000]]
[[7 7]
 [7 7]]
[10 13 16 19 22]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [5]:
# Print the number of `my_array`'s dimensions
print(a.ndim)

# Print the number of `my_array`'s elements
print(a.size)

# Print information about `my_array`'s memory layout
#print(a.flags)

# Print the length of one array element in bytes
print(a.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print(a.nbytes)

2
12
8
96


In [6]:
# Print the length of `my_array`
print(len(a))

print(a)

# Change the data type of `my_array`
a.astype(float)

3
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.random.random((3,4))
print(y)

# Check shape of `y`
print(y.shape)

# Add `x` and `y`
x + y

(3, 4)
[[0.75436241 0.65457397 0.53805512 0.69186476]
 [0.29203257 0.10539849 0.07803391 0.5111308 ]
 [0.24217374 0.37110332 0.02540596 0.60573921]]
(3, 4)


array([[1.75436241, 1.65457397, 1.53805512, 1.69186476],
       [1.29203257, 1.10539849, 1.07803391, 1.5111308 ],
       [1.24217374, 1.37110332, 1.02540596, 1.60573921]])

In [8]:
# Broadcasting works if one dimension of one of the numpy arrays is 1

# Initialize `x`
x = np.ones((3,4))

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.arange(4)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x - y 

(3, 4)
(4,)


array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [9]:
# The shape of the resulting array will again be the maximum size along each dimension of x and y

# Initialize `x` and `y`
x = np.ones((3, 4))
#print(x)

# y = np.random.random((5, 1, 4))
y = np.random.randint(1, 100, size=(5,1,4))
print(y)

# Add `x` and `y`
z = x + y
print(z.shape)
z

[[[72 64 16 47]]

 [[19 87 31 80]]

 [[47 71 31 61]]

 [[37 10 45 28]]

 [[67  2 45 59]]]
(5, 3, 4)


array([[[73., 65., 17., 48.],
        [73., 65., 17., 48.],
        [73., 65., 17., 48.]],

       [[20., 88., 32., 81.],
        [20., 88., 32., 81.],
        [20., 88., 32., 81.]],

       [[48., 72., 32., 62.],
        [48., 72., 32., 62.],
        [48., 72., 32., 62.]],

       [[38., 11., 46., 29.],
        [38., 11., 46., 29.],
        [38., 11., 46., 29.]],

       [[68.,  3., 46., 60.],
        [68.,  3., 46., 60.],
        [68.,  3., 46., 60.]]])

In [10]:
# Add `x` and `y`
sum = np.add(x,y)
print(sum)

# Subtract `x` and `y`
diff = np.subtract(x,y)
print(diff)

# Multiply `x` and `y`
prod = np.multiply(x,y)
print(prod)

# Divide `x` and `y`
quo = np.divide(x,y)
print(quo)

# Calculate the remainder of `x` and `y`
rem = np.remainder(x,y)
print(rem)

[[[73. 65. 17. 48.]
  [73. 65. 17. 48.]
  [73. 65. 17. 48.]]

 [[20. 88. 32. 81.]
  [20. 88. 32. 81.]
  [20. 88. 32. 81.]]

 [[48. 72. 32. 62.]
  [48. 72. 32. 62.]
  [48. 72. 32. 62.]]

 [[38. 11. 46. 29.]
  [38. 11. 46. 29.]
  [38. 11. 46. 29.]]

 [[68.  3. 46. 60.]
  [68.  3. 46. 60.]
  [68.  3. 46. 60.]]]
[[[-71. -63. -15. -46.]
  [-71. -63. -15. -46.]
  [-71. -63. -15. -46.]]

 [[-18. -86. -30. -79.]
  [-18. -86. -30. -79.]
  [-18. -86. -30. -79.]]

 [[-46. -70. -30. -60.]
  [-46. -70. -30. -60.]
  [-46. -70. -30. -60.]]

 [[-36.  -9. -44. -27.]
  [-36.  -9. -44. -27.]
  [-36.  -9. -44. -27.]]

 [[-66.  -1. -44. -58.]
  [-66.  -1. -44. -58.]
  [-66.  -1. -44. -58.]]]
[[[72. 64. 16. 47.]
  [72. 64. 16. 47.]
  [72. 64. 16. 47.]]

 [[19. 87. 31. 80.]
  [19. 87. 31. 80.]
  [19. 87. 31. 80.]]

 [[47. 71. 31. 61.]
  [47. 71. 31. 61.]
  [47. 71. 31. 61.]]

 [[37. 10. 45. 28.]
  [37. 10. 45. 28.]
  [37. 10. 45. 28.]]

 [[67.  2. 45. 59.]
  [67.  2. 45. 59.]
  [67.  2. 45. 59.]]]
[[[0.01388

In [11]:
print(x)
print(x.min())
print(x.sum())
print(x.max(axis=0))
print(x.cumsum(axis=1))
print(x.mean())
print(np.std(a))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1.0
12.0
[1. 1. 1. 1.]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
1.0
0.0


In [12]:
# `a` AND `b` 
np.logical_and(a, b)

# `a` OR `b` 
np.logical_or(a, b)

# `a` NOT `b` 
np.logical_not(a,b)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Subset, slice, index arrays

In [13]:
# Make the array `my_array`
my_2d_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print(my_2d_array)
print(my_2d_array.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [14]:
my_3d_array = np.random.randint(1, 100, size=(5,2,4))
print(my_3d_array.ndim)
print(my_3d_array)

3
[[[82 59 57  9]
  [99  8 27 22]]

 [[81 96 82 77]
  [41 83 45  9]]

 [[91 77 67 22]
  [19 15 43 87]]

 [[80 60 51 50]
  [70 42 83 13]]

 [[74 68 20 30]
  [96 69 83 83]]]


In [15]:
# Select the element at row 1 column 2
print(my_2d_array[1][2])

# Select the element at row 1 column 2
print(my_2d_array[1,2])

# Select the element at row 1, column 2 and 
print(my_3d_array[1,1,2])

7
7
45


In [16]:
# Select items at index 0 and 1
print(my_2d_array[0:2])

# Select items at row 0 and 1, column 1
print(my_2d_array[0:2,1])

# Select items at row 1
# This is the same as saying `my_3d_array[1,:,:]
print(my_3d_array[1,...])

[[1 2 3 4]
 [5 6 7 8]]
[2 6]
[[81 96 82 77]
 [41 83 45  9]]


In [17]:
# Try out a simple example
print(my_2d_array[my_2d_array<2])

# Specify a condition
bigger_than_3 = (my_3d_array >= 3)

# Use the condition to index our 3d array
print(my_3d_array[bigger_than_3])

[1]
[82 59 57  9 99  8 27 22 81 96 82 77 41 83 45  9 91 77 67 22 19 15 43 87
 80 60 51 50 70 42 83 13 74 68 20 30 96 69 83 83]


In [18]:
print(y)
print(np.sort(y, axis = 0))
print(y.transpose())
print(y.T)

[[[72 64 16 47]]

 [[19 87 31 80]]

 [[47 71 31 61]]

 [[37 10 45 28]]

 [[67  2 45 59]]]
[[[19  2 16 28]]

 [[37 10 31 47]]

 [[47 64 31 59]]

 [[67 71 45 61]]

 [[72 87 45 80]]]
[[[72 19 47 37 67]]

 [[64 87 71 10  2]]

 [[16 31 31 45 45]]

 [[47 80 61 28 59]]]
[[[72 19 47 37 67]]

 [[64 87 71 10  2]]

 [[16 31 31 45 45]]

 [[47 80 61 28 59]]]


In [19]:
first = np.array([1, 2, 3])
second = np.array([4, 5, 6])

import numpy.ma as ma

con = ma.concatenate([first, second])
print(con.data)

print(ma.concatenate([first, second]))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [20]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

for i in range(4):
    assert square[:, i].sum() == 34
    assert square[i, :].sum() == 34


assert square[:2, :2].sum() == 34

assert square[2:, :2].sum() == 34

assert square[:2, 2:].sum() == 34

assert square[2:, 2:].sum() == 34

In [21]:
square[2:, :2]

array([[ 9,  6],
       [ 4, 15]])

In [22]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)

numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [23]:
mask = numbers % 4 == 0
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [24]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

In [25]:
by_four = numbers[numbers % 4 == 0]

In [26]:
from numpy.random import default_rng

rng = default_rng()

In [27]:
values = rng.standard_normal(10000)

In [28]:
values[:5]

array([-1.12015286, -3.49772061,  2.25046262,  0.61332487, -0.08561112])

In [29]:
std = values.std()
std

1.0053930070598773

In [30]:
filtered = values[(values > -2 * std) & (values < 2 * std)]

In [31]:
filtered.size / values.size

0.9591

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [33]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [34]:
# split along rows

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)
# newarr = np.array_split(arr, 3)

print(arr)
print(newarr[0])
print(newarr[1])
print(newarr[2])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [35]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])


[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [36]:
## JOIN

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [37]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [38]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [39]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [40]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [41]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [42]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

array([[37, 40],
       [85, 92]])

In [43]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.vdot(a,b)

# 1*11 + 2*12 + 3*13 + 4*14 = 130

130

Bit-wise ops

In [44]:
a,b = 13,17 
print(bin(a))
print(bin(b))

print(np.bitwise_and(13, 17))

0b1101
0b10001
1


In [45]:
np.bitwise_or(13, 17)

29

In [46]:
np.invert(np.array([13], dtype = np.uint8)) 
np.binary_repr(13, width = 8) 
np.binary_repr(242, width = 8)

'11110010'

In [47]:
print('Left shift of 10 by two positions:' )
print(np.left_shift(10,2) )


print('Binary representation of 10:' )
print(np.binary_repr(10, width = 8) )
 

print('Binary representation of 40:' )
np.binary_repr(40, width = 8)  

Left shift of 10 by two positions:
40
Binary representation of 10:
00001010
Binary representation of 40:


'00101000'

In [48]:
print('Left shift of 10 by two positions:' )
print(np.right_shift(40,2) )


print('Binary representation of 10:' )
print(np.binary_repr(40, width = 8) )
 

print('Binary representation of 40:' )
np.binary_repr(10, width = 8)  

Left shift of 10 by two positions:
10
Binary representation of 10:
00101000
Binary representation of 40:


'00001010'

In [49]:
print('Concatenate two strings:' )
print(np.char.add(['hello'],[' xyz']) )

print('Concatenation example:' )
print(np.char.add(['hello', 'hi'],[' abc', ' xyz']))

Concatenate two strings:
['hello xyz']
Concatenation example:
['hello abc' 'hi xyz']


In [50]:
np.char.multiply('Hello ',3)

array('Hello Hello Hello ', dtype='<U18')

In [51]:
np.char.center('hello', 20, fillchar = '*')

array('*******hello********', dtype='<U20')

In [52]:
np.char.capitalize('hello world')

array('Hello world', dtype='<U11')

In [53]:
np.char.title('hello how are you?')

array('Hello How Are You?', dtype='<U18')

In [54]:
np.char.lower(['HELLO','WORLD']) 

array(['hello', 'world'], dtype='<U5')

In [55]:
np.char.upper('hello') 

array('HELLO', dtype='<U5')

In [56]:
print(np.char.split ('hello how are you?') )
print(np.char.split ('TutorialsPoint, Hyderabad, Telangana', sep = ','))

['hello', 'how', 'are', 'you?']
['TutorialsPoint', ' Hyderabad', ' Telangana']


In [57]:
print(np.char.splitlines('hello\nhow are you?') )
print(np.char.splitlines('hello\rhow are you?'))

#This function returns a list of elements in the array, breaking at line boundaries.

['hello', 'how are you?']
['hello', 'how are you?']


In [58]:
print(np.char.strip('ashok arora','a') )
print(np.char.strip(['arora','admin','java'],'a'))

#This function returns a copy of array with elements stripped of the specified characters leading and/or trailing in it.

shok aror
['ror' 'dmin' 'jav']


In [59]:
print(np.char.join(':','dmy') )
print(np.char.join([':','-'],['dmy','ymd']))

d:m:y
['d:m:y' 'y-m-d']


In [60]:
np.char.replace ('He is a good boy', 'is', 'was')

array('He was a good boy', dtype='<U17')

Resources:

https://www.geeksforgeeks.org/numpy-tutorial/

https://realpython.com/numpy-tutorial/

In [61]:
import numpy as np

arr = []
temp = []

for i in range(12):
    temp.append(np.random.rand()*10)
    if((len(temp)) % 3 == 0):
        arr.append(temp)
        temp = []

arr =  np.array(arr)
print(arr.flatten())
print(arr)

[0.49060917 1.50736078 0.84386624 1.61598902 0.1809786  3.92164373
 5.6686946  1.33992984 0.46014599 5.4250794  7.1908532  1.27989408]
[[0.49060917 1.50736078 0.84386624]
 [1.61598902 0.1809786  3.92164373]
 [5.6686946  1.33992984 0.46014599]
 [5.4250794  7.1908532  1.27989408]]


In [62]:
import numpy as np

arr = []
temp = []

for i in range(12):
    temp.append(np.random.rand()*10)
    if((len(temp)) % 3 == 0):
        arr.append(temp)
        temp = []

arr =  np.array(arr)
print(arr.flatten())
print(arr)

[0.69308872 2.73930696 5.76454236 8.46103504 8.38566795 0.26245862
 0.36197415 6.55462998 7.89095589 1.45732795 0.98258829 5.66310591]
[[0.69308872 2.73930696 5.76454236]
 [8.46103504 8.38566795 0.26245862]
 [0.36197415 6.55462998 7.89095589]
 [1.45732795 0.98258829 5.66310591]]


In [63]:
import numpy as np

a = np.array( [[21,15, 19, 18, 17],[16, 20, 14, 13, 12], [11, 10 , 9 , 8 , 7], [6 , 5,  4,  3,  2]])
b = a[:,1]
b = sorted(b)
c = a.copy()
k = 0
for i in b:
    index = np.where(a[:,1] == i)
    c[k] = a[index]
    k+=1

print(c)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [21 15 19 18 17]
 [16 20 14 13 12]]
